name: OWASP
on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches: [ master ]


jobs:
  owasp:
    name: Dependency-Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
      - name: Maven
        run:  mvn --errors --batch-mode -Powasp dependency-check:check
